### ISSUE TITLE
Multiple data

### ISSUE THREAD

**Issue by jurjendevries** [bubelov/btcmap-android#1]
Hi,

This is a really great open source tool, but there is already also one on the web which is called http://coinmap.org/ . I can't find where your data is from, but it seems that there are 2 sources (one for your app, and one at http://coinmap.org/api/ ) . We like to build a website with the map of Utrecht, The Netherlands, but don't want to have end-users / merchants ask to add their bitcoin location at 2 places, because that is not user friendly? Why are you not syncing with the other open data source, of use one of the 2 open data sources as one source for http://coinmap.org/ & this app? Please see http://coinmap.org/api/ for the open data.

Kind regards,

Jurjen de Vries

**Comment by bubelov** [comment]
@jurjendevries 

Hi,

This app uses OpenStreetMap as the main data source. It also uses CoinAtmRadar to fetch Bitcoin ATMs. Any data added to those data sources will be visible in the app.

Do you know what is the data source for coinmap? If they also use OpenStreetMap you can just add your data here and it will be available everywhere.

**Comment by jurjendevries** [comment]
@bubelov 
Hi Igor,
I'm not involved with the http://coinmap.org/api/ website, only an end-user. But what I see at http://coinmap.org/api/ is:
---
'Data served and stored using this API are licensed under the Open Data Commons Open Database License (ODbL) by the OpenStreetMap Foundation (OSMF). You are free to copy, distribute, transmit and adapt our data, as long as you credit coinmap and its contributors. If you alter or build upon our data, you may distribute the result only under the same licence.'
---

But the data is not equal between Coins (Android) and Coinmap (web). For example I added coinmap.org/venue/8785 half a year ago, but it is not visible in Coins.

Kind regards,
Jurjen

**Comment by bubelov** [comment]
@jurjendevries 

Hi. It looks like they just read data from OpenStreetMap but they do not write it back. You probably added your data via coinmap.org so it will be available only on coinmap.org. I found this exact place on OpenStreetMap:

https://www.openstreetmap.org/node/2458123835

This place **doesn't** have Bitcoin payment method. Here is the place nearby:

https://www.openstreetmap.org/node/2561116299

This place should be visible everywhere (Coinmap, Coins and many other apps) because it has special tag: "**payment:bitcoin = yes**"

You can add this tag to any place on OpenStreetMap and it will be also visible for many apps that use it as a data source. If you use Coinmap/Coins to add places it will be available only for those apps. I think that the best option for you is to start using OpenStreetMap.

On the long term, I will consider possibility of syncing with Coinmap but it's not guaranteed because I'm not sure they allow to filter places based on origin (it's the most reliable way to avoid duplicates)
