### ISSUE TITLE
BTC Map origin

### ISSUE THREAD

**Issue by PanderMusubi** [bubelov/btcmap-android#17]
List in README and in the app the origin of the data of the BTC Map, e.g. https://btcmap.org/ and link where people can update that map.

**Comment by PanderMusubi** [comment]
Ah, editing is done via https://www.openstreetmap.org on key `payment:bitcoin`

**Comment by bubelov** [comment]
@PanderMusubi well, it's not that simple, unfortunately

You are right, the only source of data is OSM and if you make edits there, those edits will be visible in the app in about 24 hours

You can also check this repo for daily changes, it's completely transparent and it syncs with OSM once a day: https://github.com/bubelov/btcmap-data

As you can see, the actual query it does looks like this:
```
[out:json][timeout:300];
(
    node["currency:XBT"="yes"];
    way["currency:XBT"="yes"];
    relation["currency:XBT"="yes"];
    node["currency:BTC"="yes"];
    way["currency:BTC"="yes"];
    relation["currency:BTC"="yes"];
    node["payment:bitcoin"="yes"];
    way["payment:bitcoin"="yes"];
    relation["payment:bitcoin"="yes"];
);
out meta geom;
```

It's clear that `payment:bitcoin` is the most popular tag, but OSM Wiki says that it's better to recognize Bitcoin as a currency, not a payment method. That's why there are many places which have `currency:XBT` or `currency:BTC` tags. I'd say `payment:bitcoin` is fine, but it would be nice to also add currency tags. I like `BTC` more, but it breaks ISO standard, so some people use `XBT`. It's messy and different people prefer different tags, so the app just grabs them all.

**Comment by PanderMusubi** [comment]
Thanks for the insight

**Comment by bubelov** [comment]
Fixed in https://github.com/bubelov/btcmap-android/commit/f59ae8ab9bc6cdcf5716640b4fb216c4b21c62c3
