### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Stemby** [bubelov/btcmap-android#3]
Hi,
as bitcoiner and OSM contributor I'd like to try your app, but I don't install anything from Google Play (not even APKs).

Is it possible to publish Coins on F-Droid?

Thank you very much!

Carlo

**Comment by bubelov** [comment]
@Stemby 

Hi Carlo,

There is no need to go to Google Play. You can download the APK directly from the GitHub. Each release has the APK attached to it.

The app itself allows you to use Google auth but it's completely optional and there are 2 alternatives (guest mode, email auth).

**Comment by Stemby** [comment]
Thank you, @bubelov, for your reply.

Unfortunately even I don't install APKs, as I wrote.

F-Droid is a great project: I'd like to see your program in this repository.

Best regard ls,
Carlo

**Comment by bubelov** [comment]
@Stemby 

Thank you for your feedback! It takes a lot of effort to make the "pure" version of the app. Cutting dependencies on Google Play services and supporting an alternative mapping library are labour intensive tasks. Google Services are convenient and they are the preferred way of doing things for many users. I can't promise any exact date but I will consider adding an alternative builds that are suitable for repos such as F-Droid.

**Comment by Poussinou** [comment]
Hi @Stemby I don't know if you use it, but this app is available in F-Droid via the Izzy compatible repo. You can find the app [here](https://apt.izzysoft.de/fdroid/index/apk/com.bubelov.coins)

**Comment by Poussinou** [comment]
@bubelov Should we go ahead with this app on F-Droid, since Google Services aren't included anymore?

**Comment by bubelov** [comment]
@Poussinou how does it work, technically? Does F-Droid fetch and build from a master branch automatically or does it grab the sources or APK from the latest release? 

The app is still unstable and barely usable because getting rid of Play Services is not an easy task but I believe it would be easier to work on single "pure" open source flavor than to support 2 different app flavors. 

I'll continue working on this transition and I'll let you know when the app is ready to be released. I guess F-Droid would be the main distribution channel because I withdrew the app from Google Play, it's was too much of a headache to deal with their warnings and ultimatums.

**Comment by Poussinou** [comment]
Sorry for the time it took me to answer.

F-Droid builds it's own apk directly from the source code (this repo), this is why we need the full source code, including eventual api keys. All dependencies (from gradle) must be also FLOSS (this is the case here as far as I can see). The best solution is to maintain a pure FLOSS single version, I think you're right with that.

Maybe you should start with opening a [RFP](https://gitlab.com/fdroid/rfp/issues) on our side, it could be of some help. Your app is welcome at F-Droid. If you think it's usable now, we could go ahead.

**Comment by Oymate** [comment]
Closable

**Comment by bubelov** [comment]
Better late than never

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11050

**Comment by IzzySoft** [comment]
@bubelov minor fix required in your fastlane structure: the `icon.png` should be moved inside `images` to be detected. Apart from that, you app goes live in my repo in about 2h from now and then can [be found here](https://apt.izzysoft.de/fdroid/index/apk/org.btcmap). Once live at F-Droid I usually give apps a 10 days overlap before removing them from mine again – unless there's a request to keep them there for some reason or another (so just let me know in case of).

**Comment by bubelov** [comment]
@IzzySoft are you sure about the icon location? I had this "missing icon" problem with my other app:

https://f-droid.org/packages/co.appreactor.news/

And I fixed it by placing icon in the language root:

https://github.com/bubelov/news/tree/master/fastlane/metadata/android/en

I borrowed this fix from NewPipe and it seems to be working for them too. 

Also, should I worry about this?

> Fastlane language code en-US was not found or incomplete, Fastlane can't be used without it.

**Comment by IzzySoft** [comment]
I'm pretty much sure of the icon location, yes. No idea why placing it into the language root might have fixed it; that either was a co-incidence or there's a but with fdroidserver. In my own repo fdroidserver complains about "unknown files" if I place it there.

As for `en-US` locale: this is used as fallback for stuff missing with other locales and thus must be present, yes. Maybe you could rename `en` to `en-US`? For all other languages, short notation is fine.

PS: It seems I no longer receive Github notifications. This is the second comment I found "by accident" today where I got none. I just checked because I was looking into your MR…

**Comment by bubelov** [comment]
@IzzySoft all done, thanks for you help!

One more thing, would it disturb F-Droid if I include release signing config and keystore in this repo?

https://github.com/bubelov/btcmap-android/blob/cdb1f95f23e3b172341943673a1777a3e5d5bd2d/app/build.gradle.kts#L36-L45

Now it's conditional on the availability of a signing properties file. I don't include this file in the repo, so F-Droid ignores this block and uses its signing magic instead. I'm planning to include this file as well as a dummy keystore in order to allow GitHub CI generate preview releases on each commit.

Preview releases is a good way to get quick feedback and some users are less risk-averse and they don't want to wait for more stable (but slower and less frequent) F-Droid releases.

**Comment by IzzySoft** [comment]
> all done, thanks for you help!

Thanks, and gladly! Just updated metadata on my end telling it the icon is now in place :wink:

> would it disturb F-Droid if I include release signing config and keystore in this repo?

I've seen the signing block causing issues with some apps when we tried to include them, yes. But we can "patch that out" in the build recipe using a `sed` command, I just have to find an example for this… Ah, here are some:

```yaml
prebuild: sed -i -e '/if (isPlay) {/,/}/d' -e '/signingConfigs.release/d' build.gradle

init:
  - sed -i -e '/signingConfigs {/,+3d' build.gradle
```

These are basically the patterns used (the two different variants I found skimming the `*.yml`). So simply let's remember those when it comes to merging the YAML to fdroiddata then, in case those problems arise there.

> Preview releases is a good way

Indeed, and there are multiple approaches to that:

* manually add them to F-Droid (so "suggested version" still points to the stable, while users can pick the pre-releases manually)
* using a different `applicationId` for them to have them updated automatically (nice side-effect: they can be installed alongside the stable ones)
* using a different `applicationId` and having the pre-releases in my repo instead (faster updates) while keeping the stable ones with F-Droid (higher trust)

Currently your app is with my repo, it didn't yet reach F-Droid. Once it arrived there, we can see how to proceed; unless told otherwise, I then usually remove apps after an overlap of about 10 days.

**Comment by bubelov** [comment]
@IzzySoft the app has finally appeared on F-Droid, but it looks like the icon is missing:

![Screenshot from 2022-05-27 09-22-02](https://user-images.githubusercontent.com/1189245/170616251-d40ea1da-2af5-4dbd-8e7a-113c80ea3f73.png)

Any ideas on how to fix that? Could it be due to transparency layer?

https://f-droid.org/en/packages/org.btcmap/

The app page renders this icon just fine though

**Comment by IzzySoft** [comment]
Strange. But yeah, the search is a different thing I've learned. OK, one thing that could be done is waiting for the next release to be picked up. Why? At the time of the current one, there was no icon in Fastlane. Now there is. That often helps in such issues, so let's see if it does in this case as well.

**Comment by bubelov** [comment]
@IzzySoft hmm, looks like the update didn't help and it actually made things worse =) Apart from not displaying an icon, F-Droid is showing 6 app screenshots now. There are 3 screenshots for this app and there were never more than 3 screenshots. Could it be due to the fact that I removed the old heavy `png` screenshots and replaced them with size-optimized `jpg` ones?

**Comment by IzzySoft** [comment]
Yes. That's why I always say: never rename, always replace. It's a long-standing bug which unfortunately still is not fixed.

As for the icon: I'm out of ideas then. The icon shows up fine with the app details – so this might be an issue with the search engine (a part separate from website). I'm not familiar with that one. Be welcome opening an issue there: https://gitlab.com/fdroid/fdroid-website-search – but I'm afraid I cannot help with this one.

**Comment by bubelov** [comment]
@IzzySoft what do you mean by replacing, keeping the same name and extension? It doesn't track deletions?

**Comment by IzzySoft** [comment]
As stupid as it might sound: exactly that, yes… To mitigate, you can re-add 1x1 px PNGs (to overwrite the big ones) and, once that worked out, remove those 1x1px PNGs again. They will still stay at the build server, but at least save the user the bandwidth and not disturb the display too much. Once that bug is fixed soon™ (no, please don't ask), those dummies should be cleared up then.

**Comment by bubelov** [comment]
@IzzySoft got it, thanks a lot for your assistance! Closing the issue since the app is already published

**Comment by IzzySoft** [comment]
Yupp, great – and always glad to help!

**Comment by IzzySoft** [comment]
Btw: now that your app made it to F-Droid.org, are you OK with me removing it from mine (as I usually do after an overlap of about 10 days), or do you want me to keep it? You can find some pros/cons [listed here in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) should you need help with the decision.

**Comment by bubelov** [comment]
@IzzySoft is your repo compatible with F-Droid? I have a CI job which publishes APKs after each commit:

https://github.com/bubelov/btcmap-android/releases/tag/preview

If your repo is F-Droid compatible and if it can fetch the latest releases automatically, I guess it can be a great help for users who want to stay on the bleeding edge. They would be able to add you repo and get more frequent updates delivered via F-Droid

**Comment by IzzySoft** [comment]
> is your repo compatible with F-Droid?

Yes, it can be used with any F-Droid client (that was how your app became available in the F-Droid world originally). But as the linked wiki points out: signatures of your APK are not, as yours are signed by your key, while F-Droid signs with a different key (generated once per app).

> if it can fetch the latest releases automatically

Yupp, it does.

> help for users who want to stay on the bleeding edge

Indeed – and that's one of the main reasons some apps stay (multiple examples for that already). OK, then I consider that a request for keep, and set it up accordingly. With the next sync today at around 6 pm UTC, the web frontend to my repo will include a hint that your app is available in both repos, and link here for reference. Thanks Igor!

**Comment by IzzySoft** [comment]
PS: Checking your `releases/` and comparing with the metadata set up, some questions on updating arise:

* `preview` as tag-name won't work well. As the name is always the same, my update checker will have a hard time figuring if something was updated.
* would you want previews listed with my repo? If so: only previews, or the regular versions as well?

If you want previews included with my repo (but not with F-Droid's), may I suggest a tag naming pattern like `pre-<versionName>` for them? That would mean F-Droid skips those (as it was setup with the `v%v` pattern it will stick to those tags), while I could tell my updater to obtain either one of the two or even both. It's currently set to `v%v` as well; so once you decided for a tag name pattern and let me know, I will adjust accordingly (e.g. to `(v|pre)%v` to fetch both).

**Comment by bubelov** [comment]
@IzzySoft preview releases are automatically built from the latest commit, would it be possible to do the same with your repo? Not including preview releases is also fine by me, but the main branch is usually stable so it might make sense to build from it any time the latest commit changes

**Comment by IzzySoft** [comment]
Well, then let's simply keep things as they are now and it works as you just described: my repo will pick up new releases within 24h, F-Droid within 2-7 days. If regular releases are planned on a weekly basis, I see no reason to make a fuss of the pre-releases. Whoever installed the app from my repo (or play) is free to (occasionally) pick a pre-release from Github then (as signatures match). Thanks for clarification!
